[metadata]
creation_date = "2024/01/24"
updated_date = "2023/10/23"

[rule]
rule_id = "00000000-0000-0000-0000-000000000004"
author = ["Anas TASTI"]
description = "Rule 4 descr"
from = "now-6m" #this is the default value
#index = ["winlogbeat-*", "logs-endpoint.events.*", "logs-windows.*"]
#language = "kuery"

name = "Rule 4"

risk_score = 43
severity = "critical"
tags = ["WEB"]
index = ["logs-*"]
type = "threshold"

query = ''' event.dataset : zeek.http '''

[rule.threshold]
field = ["source.ip"]
value = 100


#MITRE section

[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1098"
name = "Account Manipulation"
reference = "https://attack.mitre.org/techniques/T1046/"


[rule.threat.tactic]
id = "TA0004"
name = "Privilege Escalation"
reference = "https://attack.mitre.org/tactics/TA0004/"


