[metadata]
creation_date = "2023/12/12"
updated_date = "2023/10/23"

[rule]
rule_id = "00000000-0000-0000-0000-000000000001"
author = ["Anas TASTI"]
description = "Rule 1"
from = "now-6m" #this is the default value
#index = ["winlogbeat-*", "logs-endpoint.events.*", "logs-windows.*"]
#language = "kuery"

name = " Rule 1"

risk_score = 50
severity = "low"
tags = ["WEB"]
index = ["logs-*"]
type = "threshold"

query = ''' event.dataset : zeek.http '''

[rule.threshold]
field = ["source.ip"]
value = 100


#MITRE section

[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1110"
name = "Brute Force"
reference = "https://attack.mitre.org/techniques/T1046/"


[rule.threat.tactic]
id = "TA0006"
name = "Credential Access"
reference = "https://attack.mitre.org/tactics/TA0006/"


